### ISSUE TITLE
TypeError: unsupported operand type(s) for //: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by ctwillson** [SaneBow/tflite-kws#3]
I run this script by my model,and set "--num-keywords 2 --block-len-ms 10"，but it cannot run successfully.My tflite model file 
[stream_state_external.zip](https://github.com/user-attachments/files/17320936/stream_state_external.zip)

Exception ignored from cffi callback <function _StreamBase.__init__.<locals>.callback_ptr at 0x75958ec50790>:
Traceback (most recent call last):
  File "/home/bsp/.local/lib/python3.10/site-packages/sounddevice.py", line 854, in callback_ptr
    return _wrap_callback(callback, data, frames, time, status)
  File "/home/bsp/.local/lib/python3.10/site-packages/sounddevice.py", line 2714, in _wrap_callback
    callback(*args)
  File "/home/bsp/Desktop/tflite-kws/mic_streaming.py", line 116, in callback
    kw = gkws.process(indata)
  File "/home/bsp/Desktop/tflite-kws/kws.py", line 129, in process
    kw, info = self._any_kw_triggered(scores)
  File "/home/bsp/Desktop/tflite-kws/kws.py", line 231, in _any_kw_triggered
    self._utterance_scores[label] = self._utterance_hits[label] / max(nmin, self._last_kw_ms() // self.block_ms)
TypeError: unsupported operand type(s) for //: 'NoneType' and 'int'

**Comment by ctwillson** [comment]
![image](https://github.com/user-attachments/assets/bb8fa1b7-ebe8-4339-b8ff-ebeee36d6c9a)
It appears that _last_kw_ms will be none
